install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\Users\appveyor\sbt"""
  - cmd: SET PATH=C:\Users\appveyor\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - sbt clean
test_script:
  - sbt test
cache:
  - C:\Users\appveyor\sbt
  - C:\Users\appveyor\.ivy2
